/*** Following code generated by "/home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/update_pru_config.sh 0 pru0_array.c /home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru0_config /home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru0.map" ***/

#define _PRU0_CONFIG_C_
#include <stdint.h>

// under c++ linker error with const attribute ?!
#define const

// BEGIN original hexpru --array output 
const uint32_t pru0_image_0[] = {
0x240000c0,
0x24010080,
0x0504e0e2,
0x2eff818e,
0x230007c3,
0x240001ee,
0x230013c3,
0x0502e2e2,
0x91042480,
0xe10002c3,
0x1d04e0e0,
0x81042480,
0x230010c3,
0xf10002c3,
0x0102e2e2,
0x20c30000,
0x2e87018e,
0x10eeeefe,
0x21001000,
0x230015c3,
0x21001400,
0x10000000,
0x20c30000};

const uint8_t pru0_image_1[] = {
0x01,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00,
0x00};

// END   original hexpru --array output 



// sizeof() for code image
unsigned pru0_sizeof_code(void) { 
  return sizeof(pru0_image_0) ;
}

// under c++ linker error with const attribute ?!
