/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: pru1_statemachine_slave.c
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/stdint.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/_stdint40.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: pru1_utils.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/pru-software-support-package/include/am335x/pru_cfg.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/pru-software-support-package/include/am335x/pru_ctrl.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/mailbox.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/unibus.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/ddrmem.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/iopageregister.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: pru1_buslatches.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/pru_pru_mailbox.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_statemachine_slave.object: pru1_statemachine_slave.h
