/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_main.c
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/stdint.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/_stdint40.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/stdbool.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/pru-software-support-package/include/am335x/pru_cfg.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: resource_table_empty.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/stddef.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/pru-software-support-package/include/rsc_types.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/pru-software-support-package/include/pru_types.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_utils.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/pru-software-support-package/include/am335x/pru_ctrl.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/pru_pru_mailbox.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/mailbox.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/unibus.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/ddrmem.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/iopageregister.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_buslatches.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_statemachine_arbitration.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_statemachine_dma.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_statemachine_intr.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_statemachine_slave.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_statemachine_init.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_main.object: pru1_statemachine_powercycle.h
