/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: pru1_ddrmem.c
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/stdint.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/_stdint40.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/string.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/_ti_config.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/91_3rd_party/pru-c-compile/ti-cgt-pru_2.3.1//include/linkage.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/mailbox.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/unibus.h
/home/joerg/retrocmp/dec/UniBone/10.01_base/4_deploy/pru1_ddrmem.object: /home/joerg/retrocmp/dec/UniBone/10.01_base/2_src/shared/ddrmem.h
